site_name: The AIST Experience

theme:
  name: material
  custom_dir: overrides

  font:
    text: Roboto

  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: cyan
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - navigation.top
    - search.highlight
    - content.code.copy
    - toc.follow
    - header.autohide
    - navigation.footer

# copyright: Copyright &copy; 2026 Akaash S S<br>
# Personal experiences from an internship at AIST. This website is not affiliated with or endorsed by AIST.

copyright: |
  &copy; 2026 Akaash S S<br>
  Personal experiences from an internship at AIST. This website is not affiliated with or endorsed by AIST.

extra:
  generator: false
  analytics:
    provider: google
    property: G-PRQ18MXV45

nav:
  - Home: index.md
  - Travel: travel.md
  - Accommodation: accommodation.md
  - Food: food.md
  - Shopping: shopping.md
  - Explore: explore.md

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg