site_name: The AIST Experience

theme:
  name: material
  custom_dir: overrides

  font:
    text: Roboto

  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: cyan
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - navigation.top
    - search.highlight
    - content.code.copy
    - toc.follow
    - header.autohide
    - navigation.footer

# copyright: Copyright &copy; 2026 Akaash S S<br>
# Personal experiences from an internship at AIST. This website is not affiliated with or endorsed by AIST.

copyright: |
  &copy; 2026 Akaash S S<br>
  Independent resource based on personal internship experience.

extra:
  generator: false

nav:
  - Home: index.md
  - Travel: travel.md
  - Accommodation: accommodation.md
  - Food: food.md
  - Shopping: shopping.md
  - Explore: places.md
  - Living in Japan: tips.md